apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-01-11-app
  namespace: poc
  labels:
    app: hello-01-11-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-01-11-app
  template:
    metadata:
      labels:
        app: hello-01-11-app
    spec:
      containers:
      - name: hello-01-11-app
        image: us-central1-docker.pkg.dev/elastiq-internship-chanchal-01/hello/hellow-01-11-images:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"