apiVersion: v1
kind: Service
metadata:
  name: hello-01-11-appdocker build -t my-app:latest .-service
spec:
  selector:
    app: hello-01-11-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # This exposes it externally; for local testing, use NodePort.